import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsConditionsPage = () => {
  return (
    <div className="min-h-screen bg-background bg-grid bg-radial-glow py-12 px-4">
      <div className="max-w-3xl mx-auto space-y-8">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <Link
            to="/"
            className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors mb-6"
          >
            <ArrowLeft size={16} />
            Back to Home
          </Link>

          <div className="glass-card glow-border p-8 sm:p-10 space-y-8">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold text-foreground">Terms & Conditions</h1>
              <p className="text-sm text-muted-foreground">
                Last updated: February 19, 2026
              </p>
            </div>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">1. Agreement to Terms</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                By accessing or using the Automated Review Generator service operated by
                bdcode, you agree to be bound by these Terms and Conditions. If you do not
                agree with any part of these terms, you may not use our service.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The Automated Review Generator collects client feedback, generates
                AI-powered review drafts, and facilitates posting approved reviews on
                Google Business Profile. The service communicates with users via WhatsApp
                and email.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">3. User Responsibilities</h2>
              <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1.5 ml-2">
                <li>You agree to provide accurate and truthful feedback in all forms.</li>
                <li>You acknowledge that review drafts are AI-generated based on your feedback and may require editing.</li>
                <li>You are solely responsible for the content of any review you choose to post on Google.</li>
                <li>You agree not to misuse the service for fraudulent or misleading reviews.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">4. Review Process</h2>
              <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1.5 ml-2">
                <li>Review drafts are generated by AI and presented for your approval before posting.</li>
                <li>You may approve, request edits (up to 2 revisions), or decline any draft.</li>
                <li>Approval of a review draft is your consent to post it on Google Business Profile.</li>
                <li>Consent tokens and review links expire after 14 days.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">5. Intellectual Property</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The AI-generated review drafts are created based on your feedback and become
                your content upon approval. The service itself, including its design, code,
                and branding, remains the intellectual property of bdcode.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">6. Limitation of Liability</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                bdcode shall not be liable for any indirect, incidental, or consequential
                damages arising from your use of the service. We do not guarantee that
                reviews will be published or remain on Google, as this is subject to
                Google's own policies and review guidelines.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">7. WhatsApp Communications</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                By providing your WhatsApp number, you consent to receiving messages related
                to the review process, including drafts, approval requests, and follow-up
                reminders. You may decline at any time by tapping the "Decline" button.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">8. Modifications</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                We reserve the right to modify these Terms and Conditions at any time.
                Changes will be effective immediately upon posting. Your continued use of the
                service constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-foreground">9. Contact</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                For questions about these Terms and Conditions, contact us at{" "}
                <a href="mailto:subscriptionoff12@gmail.com" className="text-primary hover:underline">
                  subscriptionoff12@gmail.com
                </a>.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsConditionsPage;
